composer refresh

diff --git a/vendor/doctrine/dbal/.travis.yml b/vendor/doctrine/dbal/.travis.yml
--- a/vendor/doctrine/dbal/.travis.yml
+++ b/vendor/doctrine/dbal/.travis.yml
@@ -18,68 +18,26 @@ env:
   - DB=mysqli
 
 before_install:
-  - |
-    if [ "x$COVERAGE" != "xyes" ]; then
-      mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || true
-    fi
+  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
 
 before_script:
   - if [[ "$DB" == "mysql" || "$DB" == "mysqli" || "$DB" == *"mariadb"* ]]; then mysql < tests/travis/create-mysql-schema.sql; fi;
-  - |
-    if [ "x$COVERAGE" == "xyes" ] && [[ ! $(php -m | grep -si xdebug) ]]; then
-      echo "xdebug is required for coverage"
-      exit 1
-    fi
 
 install:
   - rm composer.lock
   - travis_retry composer -n update --prefer-dist
 
-script:
-  - |
-    if [ "x$COVERAGE" == "xyes" ]; then
-       ./vendor/bin/phpunit --configuration tests/travis/$DB.travis.xml --coverage-clover clover.xml
-    else
-       ./vendor/bin/phpunit --configuration tests/travis/$DB.travis.xml
-    fi
-
-after_script:
-  - |
-    if [ "x$COVERAGE" == "xyes" ]; then
-      travis_retry wget https://github.com/scrutinizer-ci/ocular/releases/download/1.5.2/ocular.phar
-      travis_retry php ocular.phar code-coverage:upload --format=php-clover clover.xml
-    fi
+script: ./vendor/bin/phpunit --configuration tests/travis/$DB.travis.xml
 
 jobs:
   allow_failures:
     - php: nightly
     - stage: Coding standard
-    - env: DB=pgsql POSTGRESQL_VERSION=11.0
-
-  exclude:
-    - php: 7.1
-      env: DB=sqlite
-    - php: 7.1
-      env: DB=mysql
-    - php: 7.1
-      env: DB=mysqli
 
   include:
     - stage: Test
       php: 7.1
-      env: DB=sqlite COVERAGE=yes
-
-    - stage: Test
-      php: 7.1
-      env: DB=mysql COVERAGE=yes
-
-    - stage: Test
-      php: 7.1
-      env: DB=mysqli COVERAGE=yes
-
-    - stage: Test
-      php: 7.1
-      env: DB=mysql MYSQL_VERSION=5.7 COVERAGE=yes
+      env: DB=mysql MYSQL_VERSION=5.7
       sudo: required
       before_script:
         - bash ./tests/travis/install-mysql-5.7.sh
@@ -98,7 +56,7 @@ jobs:
 
     - stage: Test
       php: 7.1
-      env: DB=mysqli MYSQL_VERSION=5.7 COVERAGE=yes
+      env: DB=mysqli MYSQL_VERSION=5.7
       sudo: required
       before_script:
         - bash ./tests/travis/install-mysql-5.7.sh
@@ -117,7 +75,7 @@ jobs:
 
     - stage: Test
       php: 7.1
-      env: DB=mariadb MARIADB_VERSION=10.0 COVERAGE=yes
+      env: DB=mariadb MARIADB_VERSION=10.0
       addons:
         mariadb: 10.0
     - stage: Test
@@ -133,7 +91,7 @@ jobs:
 
     - stage: Test
       php: 7.1
-      env: DB=mariadb MARIADB_VERSION=10.1 COVERAGE=yes
+      env: DB=mariadb MARIADB_VERSION=10.1
       addons:
         mariadb: 10.1
     - stage: Test
@@ -149,7 +107,7 @@ jobs:
 
     - stage: Test
       php: 7.1
-      env: DB=mariadb MARIADB_VERSION=10.2 COVERAGE=yes
+      env: DB=mariadb MARIADB_VERSION=10.2
       addons:
         mariadb: 10.2
     - stage: Test
@@ -165,7 +123,7 @@ jobs:
 
     - stage: Test
       php: 7.1
-      env: DB=mariadb.mysqli MARIADB_VERSION=10.2 COVERAGE=yes
+      env: DB=mariadb.mysqli MARIADB_VERSION=10.2
       addons:
         mariadb: 10.2
     - stage: Test
@@ -181,7 +139,7 @@ jobs:
 
     - stage: Test
       php: 7.1
-      env: DB=pgsql POSTGRESQL_VERSION=9.2 COVERAGE=yes
+      env: DB=pgsql POSTGRESQL_VERSION=9.2
       services:
         - postgresql
       addons:
@@ -203,7 +161,7 @@ jobs:
 
     - stage: Test
       php: 7.1
-      env: DB=pgsql POSTGRESQL_VERSION=9.3 COVERAGE=yes
+      env: DB=pgsql POSTGRESQL_VERSION=9.3
       services:
         - postgresql
       addons:
@@ -225,7 +183,7 @@ jobs:
 
     - stage: Test
       php: 7.1
-      env: DB=pgsql POSTGRESQL_VERSION=9.4 COVERAGE=yes
+      env: DB=pgsql POSTGRESQL_VERSION=9.4
       services:
         - postgresql
       addons:
@@ -247,7 +205,7 @@ jobs:
 
     - stage: Test
       php: 7.1
-      env: DB=pgsql POSTGRESQL_VERSION=9.5 COVERAGE=yes
+      env: DB=pgsql POSTGRESQL_VERSION=9.5
       services:
         - postgresql
       addons:
@@ -269,7 +227,7 @@ jobs:
 
     - stage: Test
       php: 7.1
-      env: DB=pgsql POSTGRESQL_VERSION=9.6 COVERAGE=yes
+      env: DB=pgsql POSTGRESQL_VERSION=9.6
       services:
         - postgresql
       addons:
@@ -291,7 +249,7 @@ jobs:
 
     - stage: Test
       php: 7.1
-      env: DB=pgsql POSTGRESQL_VERSION=10.0 COVERAGE=yes
+      env: DB=pgsql POSTGRESQL_VERSION=10.0
       sudo: required
       services:
         - postgresql
@@ -321,32 +279,7 @@ jobs:
         - bash ./tests/travis/install-postgres-10.sh
 
     - stage: Test
-      php: 7.1
-      env: DB=pgsql POSTGRESQL_VERSION=11.0
-      sudo: required
-      services:
-        - docker
-      before_script:
-        - bash ./tests/travis/install-postgres-11.sh
-    - stage: Test
-      php: 7.2
-      env: DB=pgsql POSTGRESQL_VERSION=11.0
-      sudo: required
-      services:
-        - docker
-      before_script:
-        - bash ./tests/travis/install-postgres-11.sh
-    - stage: Test
-      php: nightly
-      env: DB=pgsql POSTGRESQL_VERSION=11.0
-      sudo: required
-      services:
-        - docker
-      before_script:
-        - bash ./tests/travis/install-postgres-11.sh
-
-    - stage: Test
-      env: DB=sqlsrv COVERAGE=yes
+      env: DB=sqlsrv
       sudo: required
       services:
         - docker
@@ -365,7 +298,7 @@ jobs:
 
     - stage: Test
       php: 7.1
-      env: DB=pdo_sqlsrv COVERAGE=yes
+      env: DB=pdo_sqlsrv
       sudo: required
       services:
         - docker
@@ -383,24 +316,6 @@ jobs:
         - bash ./tests/travis/install-mssql.sh
 
     - stage: Test
-      env: DB=ibm_db2 COVERAGE=yes
-      sudo: required
-      services:
-        - docker
-      before_script:
-        - bash ./tests/travis/install-db2.sh
-        - bash ./tests/travis/install-db2-$DB.sh
-    - stage: Test
-      php: 7.2
-      env: DB=ibm_db2
-      sudo: required
-      services:
-        - docker
-      before_script:
-        - bash ./tests/travis/install-db2.sh
-        - bash ./tests/travis/install-db2-$DB.sh
-
-    - stage: Test
       php: 7.1
       env: DB=sqlite DEPENDENCIES=low
       install:
@@ -414,10 +329,17 @@ jobs:
         - composer config minimum-stability dev
         - travis_retry composer update --prefer-dist
 
-    - stage: Code Quality
-      env: DB=none STATIC_ANALYSIS
-      install: travis_retry composer update --prefer-dist
-      script: vendor/bin/phpstan analyse
+    - stage: Coverage
+      php: 7.1
+      env: DB=sqlite
+      before_script:
+        - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
+        - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
+      script:
+        - ./vendor/bin/phpunit --configuration tests/travis/$DB.travis.xml --coverage-clover clover.xml
+      after_script:
+        - wget https://scrutinizer-ci.com/ocular.phar
+        - php ocular.phar code-coverage:upload --format=php-clover clover.xml
 
     - stage: Pull request coding standard
       if: type = pull_request
